all:
	inkscape -e ../chrome/icon16.png -w 16 -h 16 logo.svg
	inkscape -e ../chrome/icon48.png -w 48 -h 48 logo.svg
	inkscape -e ../chrome/icon128.png -w 128 -h 128 logo.svg
	inkscape -e ../chrome/nonpartisan.me.png -w 256 -h 256 logo.svg
