all:
	inkscape -e ../chrome/icon16.png -w 16 -h 16 logo.svg
	inkscape -e ../chrome/icon48.png -w 48 -h 48 logo.svg
	inkscape -e ../chrome/icon128.png -w 128 -h 128 logo.svg
	inkscape -e ../chrome/nonpartisan.me.png -w 256 -h 256 logo.svg
	inkscape -e apple-touch-icon-144-precomposed.png -w 144 -h 144 logo.svg
	inkscape -e apple-touch-icon-114-precomposed.png -w 114 -h 114 logo.svg
	inkscape -e apple-touch-icon-72-precomposed.png -w 72 -h 72 logo.svg
	inkscape -e apple-touch-icon-57-precomposed.png -w 57 -h 57 logo.svg
	inkscape -e favicon.png -w 64 -h 64 logo.svg
